version: '3'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - /home/ubuntu/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'

  node-exporter:
    image: prom/node-exporter
    ports:
      - '9100:9100'

  alertmanager:
    image: prom/alertmanager
    volumes:
      - /home/ubuntu/alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    ports:
      - '9093:9093'

