global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'task20'
    static_configs:
      - targets: ['node-exporter:9100']
        labels: 
          Metric: "CPU"

  - job_name: 'task21'
    static_configs:
      - targets: ['34.228.200.26:9100']
        labels:
          Metric: "VM"

